sudo: required
language: bash
notifications:
  email: true
services:
- docker
install:
- make
before_script:
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
- make build
env:
  global:
  - secure: ctEVXliJAsd8DpeLuwfxH7mmMMGa6GIq1muSTfOvChc1/OpbqpLlFMBPD36g33bmuetjVxzsMFWQA5TjRG50Liq4BH8nSqBi9Snf5ukOH4HZnh2Z0v+KzAW2Nf4Ai4Shm1m8QbXmzPkK9z+OI8eNYgjjhRGAhLUvoG04An9QhakVNDZ0vWIsgiDtW3HDDzuTib05a47Zje9WuoCHBctOd4qj50I2142SbiwCrgM+kPgbVq7cmAUUtSZq20dlHN3DgDtAKY2gcpKF7+34zPELGT1PXEZ544tpJcaWj9aX9NFsufjxgGX0krHIoYGtaBacNS32yOXLiUN2gB8plMUkDKbyObj2dSN7nMtnZyZ3F/yEGl+vTTRful01OD512URUGiOIPhP7o6oqoWfYY+pF3p4X2T5yt75d54m9tSGeb5cnGscOcrgUfRzEYv1O/WIy7YR8ANHDwm1jLO+pWVjgCb0DVJfsnW8HwaakisFT/frN5UDlhW/FlPE70tt9M86xbGNl3J3BzB4bFnymoOMbyB+CMgXvAfVn9KYHIJfFdbmyItBUPaQgLtyp1Avdu4EV4Fmfip/n2uojaZLRtsFaVJXMfJhyZkX/8H58wvmo2qdq4TDskl1lJMr/y29ywUjUsQwZs2T919sLIfLX0+v7h+yq5LQDacH9p2MwzELi/uc=
  - secure: WO74uAOekoS8Og5toZvhgcxb6R16yVYaqegatXaoLLXx4xkS+aA9oZqiTGw6Nf6v2B5JYdnsc4ys9E0ObTcM847cwEeCezmPkkXOJon3FmD8ideY8XeJjjSz61SvC7dH5ksENtGb1YqjTeisOhuMIW+rFywuru3Zcn4L87Zps9lL02dwVA9MefoVmDrNOQoS1VksGJ5vglyRmJOfQ+x7dRGo0et9H8KTN1MoBBBYtvOPslOmSJz0okFcJXkCkhYoVl/9aV55bkrcv3TJAYS5AbBWxtkJLRvTyy3ppM4ONbzvBtoQiOWLn1MaJ9rI2XHmtoXkMhj589+lVVNQ7PQkDZAxswxxPaYowQnyFctnyVKpzihOvr8/UbUD8r5MjAbdMUJsxXL+YCbQ0vRC1F5gQarpCAylHbQMRMeKAX6Q+PMGhApHnrYosJrHPOcCEtCU+cH/cnh7tx1cEUYyFIxkoiX8kG7vkaG4BOm7NrIwDEhIyIZbx1ltHXh9hO6jmv96qkEE7odtRwusVNg8OS8pzgIJKrTdpzkHFauPiOuAJKALpkrkulgwkdbFJXUPefjlJwkPUmeVphDyGJ5Xf601/R4jInR+aYTsJ7K7WaiklYCWmPQgtSHnrHgAK9sSfACRg++95VyI69mSE7nZWeMr9biEYWZtB6pd77DZSaMphWo=
